language: go

env:
  - GO111MODULE=on

before_install:
  - go mod download

script:
  - cp config/client/sap_client.yaml internal/client/
  - go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic
  - go build cmd/server/server.go
  - go build cmd/client/client.go

after_success:
  - bash <(curl -s https://codecov.io/bash)
